resolver: lts-14.15

packages:
# - '../../lmonad'
# - '../../lmonad-yesod'
# - 'dependencies/simplessh'
- 'bibifi-core'
- 'bibifi-webapp'
- 'bibifi-runner'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: 
# - lmonad-0.1.0.0
# - lmonad-yesod-1.0.0.0
# - network-ip-0.2.1.1
# - persistent-ratelimit-0.3.0.0
- git: https://github.com/jprider63/LMonad.git
  commit: e6eda2256f26aaff592106d33e9a4cb4905c014d
- git: https://github.com/jprider63/LMonad-Yesod.git
  commit: bb502ecc1192b2ca6a7668e3ae636670bd0588e9
- git: https://github.com/jprider63/persistent-ratelimit.git
  commit: 4f3f9afc748453fb2beda00d339fc3a30ad6e7a3
- git: https://github.com/jprider63/simplessh.git
  commit: c5fc4710369324ef6e4080694ba2c537480b5bc9
- smtp-mail-0.2.0.0
- gitlab-haskell-0.1.5
- docker-0.6.0.2
# - yesod-auth-oauth2-0.1.6
# - data-textual-0.3.0.2
# - text-latin1-0.3
# - text-printer-0.4
# - data-checked-0.3
# - data-dword-0.3
# - data-endian-0.1
# - type-hint-0.1
# - data-bword-0.1
# - yesod-form-1.4.10 # ,data-dword-0.3, data-endian-0.1, data-textual-0.3.0.2, text-printer-0.4, type-hint-0.1]#, data-bword-0.1, atext-latin1-0.3]
# - git: https://github.com/jprider63/LMonad.git
#   commit: 9238df9fa56e59d6afc2c6515ea22ed5418f00e3
# - git: https://github.com/jprider63/LMonad-Yesod.git
#   commit: f3469f6175e12ea3b5b08629265986921db90c4e

allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

