# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-14.15

# Local packages, usually specified by relative directory name
packages:
- '../../lmonad'
- '../../lmonad-yesod'
- '../bibifi-core'
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: 
# - lmonad-0.1.0.0
# - lmonad-yesod-1.0.0.0
# - network-ip-0.2.1.1
# - persistent-ratelimit-0.3.0.0
- git: https://github.com/jprider63/persistent-ratelimit.git
  commit: 4f3f9afc748453fb2beda00d339fc3a30ad6e7a3
# - yesod-auth-oauth2-0.1.6
# - data-textual-0.3.0.2
# - text-latin1-0.3
# - text-printer-0.4
# - data-checked-0.3
# - data-dword-0.3
# - data-endian-0.1
# - type-hint-0.1
# - data-bword-0.1
# - yesod-form-1.4.10 # ,data-dword-0.3, data-endian-0.1, data-textual-0.3.0.2, text-printer-0.4, type-hint-0.1]#, data-bword-0.1, atext-latin1-0.3]
# - git: https://github.com/jprider63/LMonad.git
#   commit: 9238df9fa56e59d6afc2c6515ea22ed5418f00e3
# - git: https://github.com/jprider63/LMonad-Yesod.git
#   commit: f3469f6175e12ea3b5b08629265986921db90c4e


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

#extra-deps:
#- git: https://gitlab.com/philnguyen/gitlab-haskell.git
#  commit: 11f8da35124fd1757e4a1b8ce6c5a22ff294c4cd
